# Generated by Django 6.0.7 on 2026-07-27 18:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='unique_venue_name_per_city_ci',
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('city'), condition=models.Q(('is_active', True)), name='unique_venue_name_per_city_ci'),
        ),
    ]
