# Generated by Django 6.0.8 on 2026-09-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organizerpayout",
            name="payouts_org_status_b89ad5_idx",
        ),
    ]
