# Generated by Django 6.0.7 on 2026-07-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("attendee", "Attendee"),
                    ("organizer", "Organizer"),
                    ("admin", "Admin"),
                ],
                default="attendee",
                max_length=20,
            ),
        ),
    ]
