# Generated by Django 6.0.8 on 2026-08-29 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models

import apps.tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_alter_booking_status"),
        ("seating", "0003_eventseat_held_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_code",
                    models.CharField(
                        default=apps.tickets.models._generate_ticket_code,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "attendee_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="bookings.booking",
                    ),
                ),
                (
                    "event_seat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket",
                        to="seating.eventseat",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking"], name="tickets_tic_booking_9d384c_idx"
                    )
                ],
            },
        ),
    ]
