# Generated by Django 6.0.7 on 2026-08-06 09:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("venues", "0002_remove_venue_unique_venue_name_per_city_ci_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("sports_match", "Sports Match"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("is_seated", models.BooleanField(default=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="event_covers/"),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="categories.category",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="TicketTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_tiers",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="TierSectionMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_section_mappings",
                        to="events.event",
                    ),
                ),
                (
                    "ticket_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_mappings",
                        to="events.tickettier",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer"], name="events_even_organiz_266ef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_active"], name="events_even_is_acti_82811f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "start_datetime"],
                name="events_even_event_t_afaaa8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("slug",),
                name="uniq_active_event_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="event_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="tickettier",
            index=models.Index(fields=["event"], name="events_tick_event_i_f747f5_idx"),
        ),
        migrations.AddIndex(
            model_name="tiersectionmapping",
            index=models.Index(fields=["event"], name="events_tier_event_i_7c72ff_idx"),
        ),
        migrations.AddConstraint(
            model_name="tiersectionmapping",
            constraint=models.UniqueConstraint(
                fields=("event", "section"), name="unique_event_section_mapping"
            ),
        ),
    ]
