# Generated by Django 6.0.8 on 2026-09-19 20:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="venues.venue",
            ),
        ),
        migrations.AddField(
            model_name="tickettier",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_tiers",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="tiersectionmapping",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier_section_mappings",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="tiersectionmapping",
            name="ticket_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_mappings",
                to="events.tickettier",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer"], name="events_even_organiz_266ef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_active"], name="events_even_is_acti_82811f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "start_datetime"],
                name="events_even_event_t_afaaa8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "description", config="english"
                ),
                name="event_search_gin_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("slug",),
                name="uniq_active_event_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="event_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("home_team__isnull", True),
                    ("away_team__isnull", True),
                    models.Q(("home_team", models.F("away_team")), _negated=True),
                    _connector="OR",
                ),
                name="event_home_away_team_distinct",
            ),
        ),
        migrations.AddIndex(
            model_name="tickettier",
            index=models.Index(fields=["event"], name="events_tick_event_i_f747f5_idx"),
        ),
        migrations.AddIndex(
            model_name="tiersectionmapping",
            index=models.Index(fields=["event"], name="events_tier_event_i_7c72ff_idx"),
        ),
        migrations.AddConstraint(
            model_name="tiersectionmapping",
            constraint=models.UniqueConstraint(
                fields=("event", "section"), name="unique_event_section_mapping"
            ),
        ),
    ]
