# Generated by Django 6.0.7 on 2026-08-06 11:16

import apps.events.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("events", "0001_initial"),
        ("sports", "0001_initial"),
        ("venues", "0002_remove_venue_unique_venue_name_per_city_ci_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_events",
                to="sports.team",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_events",
                to="sports.team",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="sports.league",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="event_covers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.events.models.validate_cover_image_size,
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("home_team__isnull", True),
                    ("away_team__isnull", True),
                    models.Q(("home_team", models.F("away_team")), _negated=True),
                    _connector="OR",
                ),
                name="event_home_away_team_distinct",
            ),
        ),
    ]
