# Generated by Django 6.0.7 on 2026-08-07 14:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("events", "0002_event_away_team_event_home_team_event_league_and_more"),
        ("sports", "0001_initial"),
        ("venues", "0002_remove_venue_unique_venue_name_per_city_ci_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "description", config="english"
                ),
                name="event_search_gin_idx",
            ),
        ),
    ]
