# Generated by Django 6.0.8 on 2026-10-02 02:02

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="team_league_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.common.validators.validate_image_upload_size,
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="team_league_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.common.validators.validate_image_upload_size,
                ],
            ),
            preserve_default=False,
        ),
    ]
