# Generated by Django 6.0.8 on 2026-09-19 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "client_secret",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Smallest currency unit (cents) -- int(round(total_amount * 100)). Never the same decimal-dollars representation as Booking.total_amount."
                    ),
                ),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payments_pa_stripe__6fe52c_idx",
                    )
                ],
            },
        ),
    ]
