# Generated by Django 6.0.8 on 2026-09-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_payment_intent_id", ""), _negated=True),
                fields=("stripe_payment_intent_id",),
                name="uniq_payment_stripe_payment_intent_id",
            ),
        ),
    ]
