# Generated by Django 6.0.8 on 2026-10-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_uniq_payment_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
