# Generated by Django 6.0.8 on 2026-09-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking_confirmation", "Booking Confirmation"),
                    ("event_cancelled_refund", "Event Cancelled Refund"),
                    ("payout_ready", "Payout Ready"),
                    ("payout_settled", "Payout Settled"),
                    ("event_reminder", "Event Reminder"),
                ],
                max_length=32,
            ),
        ),
    ]
