# Generated by Django 6.0.7 on 2026-08-11 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_event_event_search_gin_idx"),
        ("venues", "0002_remove_venue_unique_venue_name_per_city_ci_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("held", "Held"),
                            ("booked", "Booked"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_seats",
                        to="events.event",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_seats",
                        to="venues.seat",
                    ),
                ),
                (
                    "ticket_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_seats",
                        to="events.tickettier",
                    ),
                ),
            ],
            options={
                "ordering": ["seat__section", "seat__row_label", "seat__seat_number"],
            },
        ),
        migrations.CreateModel(
            name="SeatHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("held_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "event_seat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hold",
                        to="seating.eventseat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="eventseat",
            index=models.Index(
                fields=["event", "status"], name="seating_eve_event_i_348f87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventseat",
            constraint=models.UniqueConstraint(
                fields=("event", "seat"), name="unique_event_seat"
            ),
        ),
        migrations.AddIndex(
            model_name="seathold",
            index=models.Index(
                fields=["expires_at"], name="seating_sea_expires_a676bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seathold",
            index=models.Index(
                fields=["group_id"], name="seating_sea_group_i_d0afd8_idx"
            ),
        ),
    ]
