# Generated by Django 6.0.8 on 2026-09-19 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("seating", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_seats",
                to="venues.seat",
            ),
        ),
        migrations.AddField(
            model_name="eventseat",
            name="ticket_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_seats",
                to="events.tickettier",
            ),
        ),
        migrations.AddField(
            model_name="seathold",
            name="event_seat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hold",
                to="seating.eventseat",
            ),
        ),
        migrations.AddField(
            model_name="seathold",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_holds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="eventseat",
            index=models.Index(
                fields=["event", "status"], name="seating_eve_event_i_348f87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventseat",
            constraint=models.UniqueConstraint(
                fields=("event", "seat"), name="unique_event_seat"
            ),
        ),
        migrations.AddIndex(
            model_name="seathold",
            index=models.Index(
                fields=["expires_at"], name="seating_sea_expires_a676bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seathold",
            index=models.Index(
                fields=["group_id"], name="seating_sea_group_i_d0afd8_idx"
            ),
        ),
    ]
