# Generated by Django 6.0.7 on 2026-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seathold",
            name="group_id",
            field=models.UUIDField(),
        ),
    ]
