# Generated by Django 6.0.7 on 2026-08-20 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("seating", "0002_alter_seathold_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventseat",
            name="held_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_event_seats",
                to="bookings.booking",
            ),
        ),
    ]
