# Generated by Django 6.0.8 on 2026-10-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="idempotency_key",
            field=models.CharField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="source_hold_group_id",
            field=models.UUIDField(
                default="00000000-0000-0000-0000-000000000000", unique=True
            ),
            preserve_default=False,
        ),
    ]
